# Day1 DBS Prediction Model

In [1]:
import pandas as pd

In [2]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_typing',
 

In [3]:
df = pd.read_csv("DBS_SingDollar.csv")

In [4]:
df

Unnamed: 0        Date    DBS      SGD
0             1   6/20/2017  20.45  1.38925
1             2   6/19/2017  20.60  1.38707
2             3   6/16/2017  20.45  1.38324
3             4   6/15/2017  20.41  1.38378
4             5   6/14/2017  20.59  1.37595
..          ...         ...    ...      ...
117         118  12/30/2016  17.09  1.44655
118         119  12/29/2016  17.13  1.44814
119         120  12/28/2016  17.22  1.45018
120         121  12/27/2016  17.19  1.44954
121         122  12/23/2016  17.14  1.44766

[122 rows x 4 columns]

In [5]:
X = df.loc[:, ["SGD"]]
Y = df.loc[:, ["DBS"]]

In [6]:
X

SGD
0    1.38925
1    1.38707
2    1.38324
3    1.38378
4    1.37595
..       ...
117  1.44655
118  1.44814
119  1.45018
120  1.44954
121  1.44766

[122 rows x 1 columns]

In [7]:
Y

DBS
0    20.45
1    20.60
2    20.45
3    20.41
4    20.59
..     ...
117  17.09
118  17.13
119  17.22
120  17.19
121  17.14

[122 rows x 1 columns]

In [15]:
!pip install sklearn -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1309 sha256=0d5b099a07119080925dbc5d5bd64edadabe46993aea90e161baa2909c19eb62
  Stored in directory: c:\users\simon\appdata\local\pip\cache\wheels\b5\39\b2\13b2d6aa5d88f4ef3d456f394d2bc36d2d1132ad8400657567
Successfully built sklearn


In [9]:
from sklearn import linear_model

In [10]:
model = linear_model.LinearRegression()

In [11]:
model.fit(X, Y)

LinearRegression()

In [12]:
model.coef_

array([[-50.60094302]])

In [13]:
model.intercept_

array([90.22858515])

In [17]:
# Model is 
# DBS = (-50.6 * SGD) + 90.2

In [18]:
pred = model.predict(X)
pred

array([[19.93122506],
       [20.04153512],
       [20.23533673],
       [20.20801222],
       [20.6042176 ],
       [20.31225016],
       [20.18473578],
       [20.196374  ],
       [20.26266124],
       [20.30466002],
       [20.43723449],
       [20.3198403 ],
       [20.3466588 ],
       [20.06885962],
       [20.23736076],
       [20.13109878],
       [20.06278751],
       [20.36335711],
       [20.0784738 ],
       [20.17107353],
       [19.8958044 ],
       [20.07442573],
       [20.13464085],
       [19.74298955],
       [19.90288853],
       [19.65342588],
       [19.51427329],
       [19.18789721],
       [19.00978189],
       [18.81648629],
       [19.08163523],
       [19.13628424],
       [19.35235027],
       [19.52692353],
       [19.70149678],
       [19.51933338],
       [19.53400766],
       [19.59068071],
       [19.68479847],
       [19.76120589],
       [19.56183818],
       [19.50263507],
       [19.47784061],
       [19.59776485],
       [19.49150286],
       [19

In [19]:
# SSE: Sum of sqrt Error
# MSE: Mean squared error
# RMSE: root-mean-square deviation

In [20]:
from sklearn.metrics import mean_squared_error

In [21]:
rmse = mean_squared_error(Y, pred) ** 0.5
rmse

0.6283698867042165

## Desicion Tree

In [22]:
from sklearn import tree

In [23]:
model = tree.DecisionTreeRegressor()

In [24]:
model.fit(X, Y)
pred = model.predict(X)
print(mean_squared_error(Y, pred) ** 0.5)

0.16306113708124784


In [26]:
from sklearn import ensemble

In [27]:
model = ensemble.GradientBoostingRegressor()

In [28]:
model.fit(X, Y)
pred = model.predict(X)
print(mean_squared_error(Y, pred) ** 0.5)

0.23760405149356084


E:\Anaconda3\Install\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [29]:
dir(model)

['_SUPPORTED_LOSS',
 '__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_initialized',
 '_check_n_features',
 '_check_params',
 '_clear_state',
 '_compute_partial_dependence_recursion',
 '_estimator_type',
 '_fit_stage',
 '_fit_stages',
 '_get_param_names',
 '_get_tags',
 '_init_state',
 '_is_initialized',
 '_make_estimator',
 '_more_tags',
 '_raw_predict',
 '_raw_predict_init',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_resize_state',
 '_rng',
 '_staged_raw_predict',
 '_validate_data',
 '_va

In [31]:
model = ensemble.AdaBoostRegressor()
model.fit(X, Y)
pred = model.predict(X)
print(mean_squared_error(Y, pred) ** 0.5)

0.5229470498502892


E:\Anaconda3\Install\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [32]:
model = ensemble.BaggingRegressor()

In [33]:
model.fit(X, Y)
pred = model.predict(X)
print(mean_squared_error(Y, pred) ** 0.5)

0.28280157106609205


E:\Anaconda3\Install\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [34]:
from sklearn import svm

In [35]:
model = svm.SVR()

In [36]:
model.fit(X, Y)
pred = model.predict(X)
print(mean_squared_error(Y, pred) ** 0.5)

0.5790285268311436


E:\Anaconda3\Install\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
